// flow-typed signature: cd22a2798812f08dafef985d9f488aca
// flow-typed version: <<STUB>>/@types/compression_v^0.0.36/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/compression' {
  declare module.exports: any;
}
