// flow-typed signature: fb1ad333e990ab9c7b1598c4dd78afed
// flow-typed version: <<STUB>>/@types/convict_v^4.2.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/convict'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/convict' {
  declare module.exports: any;
}
