// flow-typed signature: 56c61f6a0c1534199270526efdb7542b
// flow-typed version: <<STUB>>/@types/date-fns_v^2.6.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/date-fns'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/date-fns' {
  declare module.exports: any;
}
