// flow-typed signature: 81ab53ae445921ca81c4c2b3894b9895
// flow-typed version: <<STUB>>/@types/enzyme_v^3.1.10/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/enzyme' {
  declare module.exports: any;
}
