// flow-typed signature: 75bcce73dd8e3c4ba71fe549e4f824e6
// flow-typed version: <<STUB>>/@types/history_v^4.6.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/history' {
  declare module.exports: any;
}
