// flow-typed signature: 9b32ca09b0f99a4675a98a479a7d452e
// flow-typed version: <<STUB>>/@types/react-router_v^4.0.24/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router' {
  declare module.exports: any;
}
