// flow-typed signature: 332b433155b19b04b2c2b3a075091764
// flow-typed version: <<STUB>>/@types/react_v^16.3.13/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
