// flow-typed signature: 7d3d259632e3d39206b583512a5655a9
// flow-typed version: <<STUB>>/@types/redux-devtools-extension_v^2.13.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/redux-devtools-extension'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/redux-devtools-extension' {
  declare module.exports: any;
}
