// flow-typed signature: 8a5391acba3ad3bbacf0494724af5e8e
// flow-typed version: <<STUB>>/@types/webpack_v^4.1.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/webpack' {
  declare module.exports: any;
}
